<template>
    <transition name="show">
        <div v-if="errors.length > 0" class="pop-up app-error">
            <h1 class="title">App {{errors.length > 1 ? "errors" : "error"}} !</h1>
            <p class="message">You can help me debug this issue by uploading a zip file generated by the button under error message, send it to https://github.com/aymericingargiola/repentance-run-tracker/issues, the zip file will only contains logs and app datas.</p>
            <ul class="error-area">
                <template v-for="(error, eridx) in errors">
                    <li class="error" :key="eridx">
                        {{error}}
                    </li>
                </template>
            </ul>
            <div class="actions">
                <div class="btn generate">
                    <button @click="generateZipDump()">Generate zip</button>
                </div>
                <div class="btn close">
                    <button @click="restartApp()">Restart app</button>
                </div>
            </div>
            <a href="#" ref="downloadZip"></a>
        </div>
    </transition>
</template>

<script>
export default {
    name: "AppError",
    data() {
        return {
            errors: []
        }
    },
    mounted() {
        window.ipc.on('SYNC_SEND_APP_ERROR', (response) => {
            console.log(response)
            if(!this.errors.includes(response.error.stack)) this.errors.push(response.error.stack)
        })
        window.ipc.on('ASK_ERROR_ZIP', (response) => {
            console.log(response)
            const file = new Blob([response.datas], {type: "application/zip"});
            this.$refs.downloadZip.setAttribute('href', URL.createObjectURL(file))
            this.$refs.downloadZip.download = response.fileName
            this.$refs.downloadZip.click()
        })
    },
    computed: {
    },
    methods: {
        generateZipDump() {
            window.ipc.send('ASK_ERROR_ZIP')
        },
        restartApp() {
            window.ipc.send('RESTART_APP')
        },
    },
};
</script>

<style lang="scss">
@import "../../assets/styles/scss/vars/_colors";
.pop-up.app-error {
    position: fixed;
    background-color: $paper-white-darker;
    left: 50%;
    top: 50%;
    transform: translate(-50%, -50%);
    width: 80%;
    height: 80%;
    z-index: 999;
    border-radius: 20px;
    padding: 20px;
    box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.2);
    display: flex;
    flex-direction: column;
    .error-area {
        text-align: left;
        color: $red-a2;
        font-family: sans-serif;
        text-shadow: rgba(0, 0, 0, 1);
        padding: 10px;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.05);
        border-radius: 10px;
        .error {
            margin: 10px 0px;
        }
    }
    .actions {
        margin-top: 20px;
        margin-left: auto;
        margin-right: auto;
        display: flex;
        flex-direction: row;
        > div {
            margin: 0px 10px;
        }
    }
    .title {

    }
    &.fade-enter-active, &.fade-leave-active {
        transition: opacity .5s;
    }
    &.fade-enter, .fade-leave-to {
        opacity: 0;
    }
}
</style>